<a href="https://colab.research.google.com/github/zenilist/DataAnalytics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem 1.
Write a Python/NumPy code block that finds the distinct/unique common items between these two
arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.

In [223]:
import numpy as np
import pandas as pd
from numpy import genfromtxt

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
print(a)
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(b)

#source code https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-18.php
common_items = np.intersect1d(a,b)
print(common_items)


[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
[2 4]


#Problem 2.
Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.
1   6    11
2   7    12
3   8    13
4   9    14
5   10  15

In [224]:
y = np.array([1, 6, 11, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15]).reshape(5,3)
y


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

#Problem 3.
The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

In [38]:
x = y.flatten()
x

array([ 1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14,  5, 10, 15])

#Problem 4.
Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

In [226]:
#source code: https://stackoverflow.com/questions/7372316/how-to-make-a-2d-numpy-array-a-3d-array
z = np.reshape(y, y.shape + (1,))
z

array([[[ 1],
        [ 6],
        [11]],

       [[ 2],
        [ 7],
        [12]],

       [[ 3],
        [ 8],
        [13]],

       [[ 4],
        [ 9],
        [14]],

       [[ 5],
        [10],
        [15]]])

#Problem 5.
Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.

In [227]:
threeD_twoD = z.flatten().reshape(5,3)
threeD_twoD

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

#Problem 6.
You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [228]:
#source code: https://stackoverflow.com/questions/40055835/removing-elements-from-an-array-that-are-in-another-array

a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
c = [i for i in a if i not in b]
c

[7, 15, 1, 8]

#Problem 7.
Answer the following questions about the accompanying data file.


In [222]:
#source code: https://www.marsja.se/how-to-convert-a-pandas-dataframe-to-a-numpy-array/
df = pd.read_csv("https://raw.githubusercontent.com/zenilist/DataAnalytics/main/Module6_Data.csv")
daily_water_consumption = df['NYC Consumption(Million gallons per day)'].to_numpy(np.float64)
daily_water_consumption
per_capita_consumption = df['Per Capita(Gallons per person per day)'].to_numpy(np.float64)
population = df['New York City Population'].to_numpy(np.int64)
year = df['Year'].to_numpy(np.int64)

1. What is the maximum yearly NYC consumption of water in millions of gallons per day?


In [221]:

max_consumption_1 = max(daily_water_consumption)
print(max_consumption_1)

1512.0


2. How many calendar years are represented within this data set? NumPy's shape command is one way to find
out

In [220]:
total_years = np.shape(year)[0]
print(total_years)

39


3. What is the mean and the standard deviation of the per capita daily water consumption?


In [219]:
per_capita_consumption.mean()

160.30769230769232

4. What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [218]:
pop_diff = np.diff(population)
print(pop_diff)

[-30461  17602  19864  72119  53290  39540  45192  23230  11243  -9544
  -8525  38851  54443  77222  64292  62582  64772  75631  84816  89401
  60618  16685  16686  16685  16686  16685  16686  16685  16686  16685
  16686 108965  77081  61281  49530  44512  21171  85025]
